### ISSUE TITLE
TagPrefixes

### ISSUE THREAD

**Issue by Brandon-T** [priore/SOAPEngine#124]
I need to send a request with the following payload:

```objective-c
[self.engine requestURL:@"http://serviceurlhere.com/service.asmx" soapAction:@"https://serviceurlhere.com/SOAPAction" completeWithDictionary:^(NSInteger statusCode, NSDictionary *dict) {
        
    } failWithError:^(NSError *error) {
        
    }];
```

```xml
<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" xmlns:pos="https://my-url-here/namespace">
	<soapenv:Header>
		<prefix:AuthHeader>
			<prefix:Username>Username</prefix:Username>
			<prefix:Password>Password</prefix:Password>
		</prefix:AuthHeader>
	</soapenv:Header>
	<soapenv:Body>
		<prefix:AccountInfo>
			<AccountInquiryMessage>
				<AccountNumber>AccountNumberHere</AccountNumber>
			</AccountInquiryMessage>
		</prefix:AccountInfo>
	</soapenv:Body>
</soapenv:Envelope>
```

Using the SOAPEngine, I can't get it to prefix the ROOT tag in the body..

I had to do:

```objective-c
- (NSMutableURLRequest*)soapEngine:(SOAPEngine*)soapEngine didBeforeSendingURLRequest:(NSMutableURLRequest*)request {
    
    NSString *xmlString = [[NSString alloc] initWithData:[request HTTPBody] encoding:NSUTF8StringEncoding];
    
    for (NSString *tag in self.tagsToReplace) {
        NSRegularExpression *expr = [[NSRegularExpression alloc] initWithPattern:[NSString stringWithFormat:@"<%@\\sxmlns.*?>", tag] options:0 error:nil];
        
        xmlString = [expr stringByReplacingMatchesInString:xmlString options:0 range:NSMakeRange(0, xmlString.length) withTemplate:[NSString stringWithFormat:@"<prefix:%@>", tag]];
        
        xmlString = [xmlString stringByReplacingOccurrencesOfString:[NSString stringWithFormat:@"</%@>", tag] withString:[NSString stringWithFormat:@"</prefix:%@>", tag]];
    }
    
    [request setHTTPBody:[xmlString dataUsingEncoding:NSUTF8StringEncoding]];
    return request;
}
```

By root tag, I mean the "AccountInfo" tag. Is there really no way to prefix the tags or specify which tags should be prefixed? There should be a way to prefix at least the root tag within the body tag.

Even for the header tags, I had to prefix them myself and set the header. Is there something I'm missing?

**Comment by priore** [comment]
Hi

```objective-c
    soap.envelope = @"xmlns:prefix=\"http://prefix-scherma-url\"";
    soap.authorizationMethod = SOAP_AUTH_CUSTOM;
    NSDictionary *auth = @{@"prefix:Username": @"user", @"prefix:Password": @"pwd"};
    soap.header = @{@"prefix:AuthHeader": auth}; // (SOAPEnginve v1.28)
    NSDictionary *accountNumber =  @{@"AccountNumber": @(123456)};
    [soap setValue:accountNumber forKey:@"AccountInquiryMessage"];
    [soap requestURL:@"http://service-url"
          soapAction:@"prefix:AccountInfo"];

```

**Comment by Brandon-T** [comment]
@priore If I do that, I get:

```objective-c
System.Web.Services.Protocols.SoapException: Server did not recognize the value of HTTP Header SOAPAction: prefix:AccountInfo.
   at System.Web.Services.Protocols.Soap11ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing)
```

I ended up doing your code but also had to do:

```objective-c
- (NSMutableURLRequest*)soapEngine:(SOAPEngine*)soapEngine didBeforeSendingURLRequest:(NSMutableURLRequest*)request {
    
    NSMutableDictionary *headers = [request.allHTTPHeaderFields mutableCopy];
    [headers setValue:[@"http://service-url.com/AccountInfo"] forKey:@"SOAPAction"];
    [request setAllHTTPHeaderFields:headers];
    return request;
}
```

**Comment by priore** [comment]
Usually the soapAction parameter no has a prefix, as in your case prefix:AccountInfo, usually is enough to pass http://your-address/AccountInfo and this construct a xml body like this:

```xml
<soapenv:Body>
        <AccountInfo xmlns="http://your-address">
            <AccountInquiryMessage>
                <AccountNumber>AccountNumberHere</AccountNumber>
            </AccountInquiryMessage>
        </AccountInfo>
</soapenv:Body>
```

in this case the "prefix" is replaced automatically with xmlns = "http: // your-address", this is the correct way, you don't need use "prefix:" in the body, and you do not need to set a custom SOAPAction in header request, this is set automatically.

**Comment by Brandon-T** [comment]
@priore Without prefix in the body, the server rejects it. Basically, if I use "AccountInfo" instead of "prefix:AccountInfo", the server will reject it with error code 3003. That is why I modified the header to accept the URL and the action to be: "prefix:AccountInfo".

**Comment by priore** [comment]
ok, probably because the service is not standard Microsoft?
In this case, remember to set the property named "responseHeader" to YES

**Comment by Brandon-T** [comment]
Ahh thanks for the tip! :)
